# Generated by Django 2.1.2 on 2018-10-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_img_href',
            field=models.CharField(default='https://www.google.co.in/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjqoNjyoZjeAhXKeX0KHRE2CykQjRx6BAgBEAU&url=http%3A%2F%2Fwww.qygjxz.com%2Fnew-picture.html&psig=AOvVaw2LZeceai3NfLcaShE8ntnE&ust=1540236408049785', max_length=4000),
        ),
    ]
